[package]
name = "libretro-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = { version = "0.8.20", features = ["derive"] }

[build-dependencies]
bindgen = "0.72.1"
